# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_profile(self):
        """Test case for get_user_profile

        Get user's profile  # noqa: E501
        """
        pass

    def test_register_user(self):
        """Test case for register_user

        Register a new user  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Reset the user's password  # noqa: E501
        """
        pass

    def test_reset_password_code(self):
        """Test case for reset_password_code

        Register a code to reset the password  # noqa: E501
        """
        pass

    def test_update_user_password(self):
        """Test case for update_user_password

        Update user's password  # noqa: E501
        """
        pass

    def test_update_user_profile(self):
        """Test case for update_user_profile

        Update user's profile  # noqa: E501
        """
        pass

    def test_verify_email(self):
        """Test case for verify_email

        Verify user's email address  # noqa: E501
        """
        pass

    def test_verify_password_code(self):
        """Test case for verify_password_code

        Verify a reset password code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
