# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subscriptions_api import SubscriptionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_opt_out_entry(self):
        """Test case for add_opt_out_entry

        Add opt-out entry  # noqa: E501
        """
        pass

    def test_add_package_subscription(self):
        """Test case for add_package_subscription

        Add subscription  # noqa: E501
        """
        pass

    def test_delete_opt_out_entry(self):
        """Test case for delete_opt_out_entry

        Delete opt-out entry  # noqa: E501
        """
        pass

    def test_delete_package_subscription(self):
        """Test case for delete_package_subscription

        Delete subscription  # noqa: E501
        """
        pass

    def test_get_package_user_subscriptions(self):
        """Test case for get_package_user_subscriptions

        Get user's subscriptions for the given package  # noqa: E501
        """
        pass

    def test_get_user_opt_out_entries(self):
        """Test case for get_user_opt_out_entries

        Get user's opt-out entries  # noqa: E501
        """
        pass

    def test_get_user_subscriptions(self):
        """Test case for get_user_subscriptions

        Get user's subscriptions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
