# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.kube_armor_policies_package_data import KubeArmorPoliciesPackageData  # noqa: E501
from swagger_client.rest import ApiException


class TestKubeArmorPoliciesPackageData(unittest.TestCase):
    """KubeArmorPoliciesPackageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKubeArmorPoliciesPackageData(self):
        """Test KubeArmorPoliciesPackageData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.kube_armor_policies_package_data.KubeArmorPoliciesPackageData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
