# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.integrations_api import IntegrationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntegrationsApi(unittest.TestCase):
    """IntegrationsApi unit test stubs"""

    def setUp(self):
        self.api = IntegrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_harbor_replication_dump(self):
        """Test case for get_harbor_replication_dump

        Get Harbor replication dump  # noqa: E501
        """
        pass

    def test_get_helm_exporter_dump(self):
        """Test case for get_helm_exporter_dump

        Get Helm exporter dump  # noqa: E501
        """
        pass

    def test_get_nova_dump(self):
        """Test case for get_nova_dump

        Get Nova dump  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
