# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.packages_api import PackagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPackagesApi(unittest.TestCase):
    """PackagesApi unit test stubs"""

    def setUp(self):
        self.api = PackagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_production_usage(self):
        """Test case for add_production_usage

        Add organization to package's production users list  # noqa: E501
        """
        pass

    def test_delete_production_usage(self):
        """Test case for delete_production_usage

        Delete organization from package's production usage list  # noqa: E501
        """
        pass

    def test_generate_changelog_md(self):
        """Test case for generate_changelog_md

        Get package's changelog in markdown format  # noqa: E501
        """
        pass

    def test_get_argo_templates_details(self):
        """Test case for get_argo_templates_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_argo_templates_version_details(self):
        """Test case for get_argo_templates_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_backstage_plugins_details(self):
        """Test case for get_backstage_plugins_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_backstage_plugins_version_details(self):
        """Test case for get_backstage_plugins_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_chart_values(self):
        """Test case for get_chart_values

        Get chart values  # noqa: E501
        """
        pass

    def test_get_container_image_details(self):
        """Test case for get_container_image_details

        Get container image details  # noqa: E501
        """
        pass

    def test_get_container_image_version_details(self):
        """Test case for get_container_image_version_details

        Get container image details  # noqa: E501
        """
        pass

    def test_get_core_dns_plugin_details(self):
        """Test case for get_core_dns_plugin_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_core_dns_plugin_version_details(self):
        """Test case for get_core_dns_plugin_version_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_falco_rules_details(self):
        """Test case for get_falco_rules_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_falco_rules_version_details(self):
        """Test case for get_falco_rules_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_gatekeeper_policies_details(self):
        """Test case for get_gatekeeper_policies_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_gatekeeper_policies_version_details(self):
        """Test case for get_gatekeeper_policies_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_helm_chart_templates(self):
        """Test case for get_helm_chart_templates

        Get the templates for a Helm chart package  # noqa: E501
        """
        pass

    def test_get_helm_package_details(self):
        """Test case for get_helm_package_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_helm_package_version_details(self):
        """Test case for get_helm_package_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_helm_plugin_details(self):
        """Test case for get_helm_plugin_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_helm_plugin_version_details(self):
        """Test case for get_helm_plugin_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_keda_scaler_details(self):
        """Test case for get_keda_scaler_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_keda_scaler_version_details(self):
        """Test case for get_keda_scaler_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_keptn_integrations_details(self):
        """Test case for get_keptn_integrations_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_keptn_integrations_version_details(self):
        """Test case for get_keptn_integrations_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_knative_client_plugin_integrations_details(self):
        """Test case for get_knative_client_plugin_integrations_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_knative_client_plugins_version_details(self):
        """Test case for get_knative_client_plugins_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_kube_armor_policies_details(self):
        """Test case for get_kube_armor_policies_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_kube_armor_policies_version_details(self):
        """Test case for get_kube_armor_policies_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_kubectl_plugin_details(self):
        """Test case for get_kubectl_plugin_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_kubectl_plugin_version_details(self):
        """Test case for get_kubectl_plugin_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_kubewarden_policies_details(self):
        """Test case for get_kubewarden_policies_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_kubewarden_policies_version_details(self):
        """Test case for get_kubewarden_policies_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_kyverno_policies_details(self):
        """Test case for get_kyverno_policies_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_kyverno_policies_version_details(self):
        """Test case for get_kyverno_policies_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_olm_operator_details(self):
        """Test case for get_olm_operator_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_olm_operator_version_details(self):
        """Test case for get_olm_operator_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_opa_policies_details(self):
        """Test case for get_opa_policies_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_opa_policies_version_details(self):
        """Test case for get_opa_policies_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_package_changelog(self):
        """Test case for get_package_changelog

        Get package changelogs  # noqa: E501
        """
        pass

    def test_get_package_security_report(self):
        """Test case for get_package_security_report

        Get package security report  # noqa: E501
        """
        pass

    def test_get_package_stars(self):
        """Test case for get_package_stars

        Get package stars  # noqa: E501
        """
        pass

    def test_get_package_stats(self):
        """Test case for get_package_stats

        Get the number of packages and releases registered  # noqa: E501
        """
        pass

    def test_get_package_summary(self):
        """Test case for get_package_summary

        Get package summary details  # noqa: E501
        """
        pass

    def test_get_package_values_schema(self):
        """Test case for get_package_values_schema

        Get package values schema  # noqa: E501
        """
        pass

    def test_get_package_views(self):
        """Test case for get_package_views

        Get the views of the package provided  # noqa: E501
        """
        pass

    def test_get_production_usage(self):
        """Test case for get_production_usage

        Get a summary of which of the organizations the user belongs to are using the package in production  # noqa: E501
        """
        pass

    def test_get_random_packages(self):
        """Test case for get_random_packages

        Get some random packages  # noqa: E501
        """
        pass

    def test_get_starred_packages_by_user(self):
        """Test case for get_starred_packages_by_user

        Get packages starred by user  # noqa: E501
        """
        pass

    def test_get_tekton_pipeline_details(self):
        """Test case for get_tekton_pipeline_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_tekton_pipeline_version_details(self):
        """Test case for get_tekton_pipeline_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_tekton_task_details(self):
        """Test case for get_tekton_task_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_tekton_task_version_details(self):
        """Test case for get_tekton_task_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_get_tinkerbell_actions_details(self):
        """Test case for get_tinkerbell_actions_details

        Get package details  # noqa: E501
        """
        pass

    def test_get_tinkerbell_actions_version_details(self):
        """Test case for get_tinkerbell_actions_version_details

        Get package version details  # noqa: E501
        """
        pass

    def test_search_packages(self):
        """Test case for search_packages

        Search packages that meet the provided criteria  # noqa: E501
        """
        pass

    def test_toggle_package_star(self):
        """Test case for toggle_package_star

        Toggle package's star  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
