# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.repositories_api import RepositoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoriesApi(unittest.TestCase):
    """RepositoriesApi unit test stubs"""

    def setUp(self):
        self.api = RepositoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_organization_repository(self):
        """Test case for add_organization_repository

        Add organization's repository  # noqa: E501
        """
        pass

    def test_add_user_repository(self):
        """Test case for add_user_repository

        Add user's repository  # noqa: E501
        """
        pass

    def test_claim_repository_ownership(self):
        """Test case for claim_repository_ownership

        Claim the ownership of a given repository  # noqa: E501
        """
        pass

    def test_claim_repository_ownership_from_organization(self):
        """Test case for claim_repository_ownership_from_organization

        Claim the ownership of a given repository  # noqa: E501
        """
        pass

    def test_delete_organization_repository(self):
        """Test case for delete_organization_repository

        Delete organization's repository  # noqa: E501
        """
        pass

    def test_delete_user_repository(self):
        """Test case for delete_user_repository

        Delete user's repository  # noqa: E501
        """
        pass

    def test_search_repositories(self):
        """Test case for search_repositories

        Search repositories that meet the provided criteria  # noqa: E501
        """
        pass

    def test_transfer_repository_ownership(self):
        """Test case for transfer_repository_ownership

        Transfer organization's repository to a different owner  # noqa: E501
        """
        pass

    def test_transfer_repository_ownership_to_organization(self):
        """Test case for transfer_repository_ownership_to_organization

        Transfer user's repository ownership to an organization  # noqa: E501
        """
        pass

    def test_update_organization_repository(self):
        """Test case for update_organization_repository

        Update organization's repository  # noqa: E501
        """
        pass

    def test_update_user_repository(self):
        """Test case for update_user_repository

        Update user's repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
