# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2008_repositories import InlineResponse2008Repositories  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2008Repositories(unittest.TestCase):
    """InlineResponse2008Repositories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008Repositories(self):
        """Test InlineResponse2008Repositories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2008_repositories.InlineResponse2008Repositories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
