# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.helm_package import HelmPackage  # noqa: E501
from swagger_client.rest import ApiException


class TestHelmPackage(unittest.TestCase):
    """HelmPackage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelmPackage(self):
        """Test HelmPackage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.helm_package.HelmPackage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
