# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.keptn_integrations_package_data import KeptnIntegrationsPackageData  # noqa: E501
from swagger_client.rest import ApiException


class TestKeptnIntegrationsPackageData(unittest.TestCase):
    """KeptnIntegrationsPackageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeptnIntegrationsPackageData(self):
        """Test KeptnIntegrationsPackageData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.keptn_integrations_package_data.KeptnIntegrationsPackageData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
