# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.webhooks_api import WebhooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_organization_webhook(self):
        """Test case for add_organization_webhook

        Add organization's webhook  # noqa: E501
        """
        pass

    def test_add_user_webhook(self):
        """Test case for add_user_webhook

        Add user's webhook  # noqa: E501
        """
        pass

    def test_delete_organization_webhook(self):
        """Test case for delete_organization_webhook

        Delete organization's webhook  # noqa: E501
        """
        pass

    def test_delete_user_webhook(self):
        """Test case for delete_user_webhook

        Delete user's webhook  # noqa: E501
        """
        pass

    def test_get_organization_webhook_details(self):
        """Test case for get_organization_webhook_details

        Get organization's webhook  # noqa: E501
        """
        pass

    def test_get_organization_webhooks(self):
        """Test case for get_organization_webhooks

        Get organization's webhooks  # noqa: E501
        """
        pass

    def test_get_user_webhook_detail(self):
        """Test case for get_user_webhook_detail

        Get user's webhook  # noqa: E501
        """
        pass

    def test_get_user_webhooks(self):
        """Test case for get_user_webhooks

        Get user's webhooks  # noqa: E501
        """
        pass

    def test_trigger_webhook_test(self):
        """Test case for trigger_webhook_test

        Trigger webhook test  # noqa: E501
        """
        pass

    def test_update_organization_webhook(self):
        """Test case for update_organization_webhook

        Update organization's webhook  # noqa: E501
        """
        pass

    def test_update_user_webhook(self):
        """Test case for update_user_webhook

        Update user's webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
