# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2008Repositories(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'running_total': 'list[list[int]]',
        'created_monthly': 'list[list[int]]'
    }

    attribute_map = {
        'total': 'total',
        'running_total': 'running_total',
        'created_monthly': 'created_monthly'
    }

    def __init__(self, total=None, running_total=None, created_monthly=None):  # noqa: E501
        """InlineResponse2008Repositories - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._running_total = None
        self._created_monthly = None
        self.discriminator = None
        self.total = total
        if running_total is not None:
            self.running_total = running_total
        if created_monthly is not None:
            self.created_monthly = created_monthly

    @property
    def total(self):
        """Gets the total of this InlineResponse2008Repositories.  # noqa: E501


        :return: The total of this InlineResponse2008Repositories.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this InlineResponse2008Repositories.


        :param total: The total of this InlineResponse2008Repositories.  # noqa: E501
        :type: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def running_total(self):
        """Gets the running_total of this InlineResponse2008Repositories.  # noqa: E501


        :return: The running_total of this InlineResponse2008Repositories.  # noqa: E501
        :rtype: list[list[int]]
        """
        return self._running_total

    @running_total.setter
    def running_total(self, running_total):
        """Sets the running_total of this InlineResponse2008Repositories.


        :param running_total: The running_total of this InlineResponse2008Repositories.  # noqa: E501
        :type: list[list[int]]
        """

        self._running_total = running_total

    @property
    def created_monthly(self):
        """Gets the created_monthly of this InlineResponse2008Repositories.  # noqa: E501


        :return: The created_monthly of this InlineResponse2008Repositories.  # noqa: E501
        :rtype: list[list[int]]
        """
        return self._created_monthly

    @created_monthly.setter
    def created_monthly(self, created_monthly):
        """Sets the created_monthly of this InlineResponse2008Repositories.


        :param created_monthly: The created_monthly of this InlineResponse2008Repositories.  # noqa: E501
        :type: list[list[int]]
        """

        self._created_monthly = created_monthly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2008Repositories, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2008Repositories):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
