# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2002(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stars': 'int',
        'starred_by_user': 'bool'
    }

    attribute_map = {
        'stars': 'stars',
        'starred_by_user': 'starred_by_user'
    }

    def __init__(self, stars=None, starred_by_user=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger"""  # noqa: E501
        self._stars = None
        self._starred_by_user = None
        self.discriminator = None
        if stars is not None:
            self.stars = stars
        if starred_by_user is not None:
            self.starred_by_user = starred_by_user

    @property
    def stars(self):
        """Gets the stars of this InlineResponse2002.  # noqa: E501


        :return: The stars of this InlineResponse2002.  # noqa: E501
        :rtype: int
        """
        return self._stars

    @stars.setter
    def stars(self, stars):
        """Sets the stars of this InlineResponse2002.


        :param stars: The stars of this InlineResponse2002.  # noqa: E501
        :type: int
        """

        self._stars = stars

    @property
    def starred_by_user(self):
        """Gets the starred_by_user of this InlineResponse2002.  # noqa: E501


        :return: The starred_by_user of this InlineResponse2002.  # noqa: E501
        :rtype: bool
        """
        return self._starred_by_user

    @starred_by_user.setter
    def starred_by_user(self, starred_by_user):
        """Sets the starred_by_user of this InlineResponse2002.


        :param starred_by_user: The starred_by_user of this InlineResponse2002.  # noqa: E501
        :type: bool
        """

        self._starred_by_user = starred_by_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2002, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
