# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KrewPluginsPackageData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'platforms': 'list[str]',
        'manifest_raw': 'dict(str, str)'
    }

    attribute_map = {
        'platforms': 'platforms',
        'manifest_raw': 'manifestRaw'
    }

    def __init__(self, platforms=None, manifest_raw=None):  # noqa: E501
        """KrewPluginsPackageData - a model defined in Swagger"""  # noqa: E501
        self._platforms = None
        self._manifest_raw = None
        self.discriminator = None
        if platforms is not None:
            self.platforms = platforms
        if manifest_raw is not None:
            self.manifest_raw = manifest_raw

    @property
    def platforms(self):
        """Gets the platforms of this KrewPluginsPackageData.  # noqa: E501


        :return: The platforms of this KrewPluginsPackageData.  # noqa: E501
        :rtype: list[str]
        """
        return self._platforms

    @platforms.setter
    def platforms(self, platforms):
        """Sets the platforms of this KrewPluginsPackageData.


        :param platforms: The platforms of this KrewPluginsPackageData.  # noqa: E501
        :type: list[str]
        """

        self._platforms = platforms

    @property
    def manifest_raw(self):
        """Gets the manifest_raw of this KrewPluginsPackageData.  # noqa: E501


        :return: The manifest_raw of this KrewPluginsPackageData.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._manifest_raw

    @manifest_raw.setter
    def manifest_raw(self, manifest_raw):
        """Sets the manifest_raw of this KrewPluginsPackageData.


        :param manifest_raw: The manifest_raw of this KrewPluginsPackageData.  # noqa: E501
        :type: dict(str, str)
        """

        self._manifest_raw = manifest_raw

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KrewPluginsPackageData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KrewPluginsPackageData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
