# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KubewardenPoliciesPackageData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kubewardenresources': 'str',
        'kubewardenmutation': 'str'
    }

    attribute_map = {
        'kubewardenresources': 'kubewarden/resources',
        'kubewardenmutation': 'kubewarden/mutation'
    }

    def __init__(self, kubewardenresources=None, kubewardenmutation=None):  # noqa: E501
        """KubewardenPoliciesPackageData - a model defined in Swagger"""  # noqa: E501
        self._kubewardenresources = None
        self._kubewardenmutation = None
        self.discriminator = None
        if kubewardenresources is not None:
            self.kubewardenresources = kubewardenresources
        if kubewardenmutation is not None:
            self.kubewardenmutation = kubewardenmutation

    @property
    def kubewardenresources(self):
        """Gets the kubewardenresources of this KubewardenPoliciesPackageData.  # noqa: E501


        :return: The kubewardenresources of this KubewardenPoliciesPackageData.  # noqa: E501
        :rtype: str
        """
        return self._kubewardenresources

    @kubewardenresources.setter
    def kubewardenresources(self, kubewardenresources):
        """Sets the kubewardenresources of this KubewardenPoliciesPackageData.


        :param kubewardenresources: The kubewardenresources of this KubewardenPoliciesPackageData.  # noqa: E501
        :type: str
        """

        self._kubewardenresources = kubewardenresources

    @property
    def kubewardenmutation(self):
        """Gets the kubewardenmutation of this KubewardenPoliciesPackageData.  # noqa: E501


        :return: The kubewardenmutation of this KubewardenPoliciesPackageData.  # noqa: E501
        :rtype: str
        """
        return self._kubewardenmutation

    @kubewardenmutation.setter
    def kubewardenmutation(self, kubewardenmutation):
        """Sets the kubewardenmutation of this KubewardenPoliciesPackageData.


        :param kubewardenmutation: The kubewardenmutation of this KubewardenPoliciesPackageData.  # noqa: E501
        :type: str
        """

        self._kubewardenmutation = kubewardenmutation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubewardenPoliciesPackageData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubewardenPoliciesPackageData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
