# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PackagespackageIDchangelogChanges(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'kind': 'ChangelogItemKind',
        'links': 'list[PackagespackageIDchangelogLinks]'
    }

    attribute_map = {
        'description': 'description',
        'kind': 'kind',
        'links': 'links'
    }

    def __init__(self, description=None, kind=None, links=None):  # noqa: E501
        """PackagespackageIDchangelogChanges - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._kind = None
        self._links = None
        self.discriminator = None
        self.description = description
        if kind is not None:
            self.kind = kind
        if links is not None:
            self.links = links

    @property
    def description(self):
        """Gets the description of this PackagespackageIDchangelogChanges.  # noqa: E501


        :return: The description of this PackagespackageIDchangelogChanges.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PackagespackageIDchangelogChanges.


        :param description: The description of this PackagespackageIDchangelogChanges.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def kind(self):
        """Gets the kind of this PackagespackageIDchangelogChanges.  # noqa: E501


        :return: The kind of this PackagespackageIDchangelogChanges.  # noqa: E501
        :rtype: ChangelogItemKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this PackagespackageIDchangelogChanges.


        :param kind: The kind of this PackagespackageIDchangelogChanges.  # noqa: E501
        :type: ChangelogItemKind
        """

        self._kind = kind

    @property
    def links(self):
        """Gets the links of this PackagespackageIDchangelogChanges.  # noqa: E501


        :return: The links of this PackagespackageIDchangelogChanges.  # noqa: E501
        :rtype: list[PackagespackageIDchangelogLinks]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PackagespackageIDchangelogChanges.


        :param links: The links of this PackagespackageIDchangelogChanges.  # noqa: E501
        :type: list[PackagespackageIDchangelogLinks]
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackagespackageIDchangelogChanges, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackagespackageIDchangelogChanges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
