# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PackageStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subscriptions': 'int',
        'webhooks': 'int'
    }

    attribute_map = {
        'subscriptions': 'subscriptions',
        'webhooks': 'webhooks'
    }

    def __init__(self, subscriptions=None, webhooks=None):  # noqa: E501
        """PackageStats - a model defined in Swagger"""  # noqa: E501
        self._subscriptions = None
        self._webhooks = None
        self.discriminator = None
        self.subscriptions = subscriptions
        self.webhooks = webhooks

    @property
    def subscriptions(self):
        """Gets the subscriptions of this PackageStats.  # noqa: E501


        :return: The subscriptions of this PackageStats.  # noqa: E501
        :rtype: int
        """
        return self._subscriptions

    @subscriptions.setter
    def subscriptions(self, subscriptions):
        """Sets the subscriptions of this PackageStats.


        :param subscriptions: The subscriptions of this PackageStats.  # noqa: E501
        :type: int
        """
        if subscriptions is None:
            raise ValueError("Invalid value for `subscriptions`, must not be `None`")  # noqa: E501

        self._subscriptions = subscriptions

    @property
    def webhooks(self):
        """Gets the webhooks of this PackageStats.  # noqa: E501


        :return: The webhooks of this PackageStats.  # noqa: E501
        :rtype: int
        """
        return self._webhooks

    @webhooks.setter
    def webhooks(self, webhooks):
        """Sets the webhooks of this PackageStats.


        :param webhooks: The webhooks of this PackageStats.  # noqa: E501
        :type: int
        """
        if webhooks is None:
            raise ValueError("Invalid value for `webhooks`, must not be `None`")  # noqa: E501

        self._webhooks = webhooks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
