# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'packages': 'int',
        'releases': 'int'
    }

    attribute_map = {
        'packages': 'packages',
        'releases': 'releases'
    }

    def __init__(self, packages=None, releases=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501
        self._packages = None
        self._releases = None
        self.discriminator = None
        if packages is not None:
            self.packages = packages
        if releases is not None:
            self.releases = releases

    @property
    def packages(self):
        """Gets the packages of this InlineResponse200.  # noqa: E501


        :return: The packages of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._packages

    @packages.setter
    def packages(self, packages):
        """Sets the packages of this InlineResponse200.


        :param packages: The packages of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._packages = packages

    @property
    def releases(self):
        """Gets the releases of this InlineResponse200.  # noqa: E501


        :return: The releases of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._releases

    @releases.setter
    def releases(self, releases):
        """Sets the releases of this InlineResponse200.


        :param releases: The releases of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._releases = releases

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
