# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeptnIntegrationsPackageData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keptnversion': 'str',
        'keptnkind': 'str'
    }

    attribute_map = {
        'keptnversion': 'keptn/version',
        'keptnkind': 'keptn/kind'
    }

    def __init__(self, keptnversion=None, keptnkind=None):  # noqa: E501
        """KeptnIntegrationsPackageData - a model defined in Swagger"""  # noqa: E501
        self._keptnversion = None
        self._keptnkind = None
        self.discriminator = None
        if keptnversion is not None:
            self.keptnversion = keptnversion
        if keptnkind is not None:
            self.keptnkind = keptnkind

    @property
    def keptnversion(self):
        """Gets the keptnversion of this KeptnIntegrationsPackageData.  # noqa: E501


        :return: The keptnversion of this KeptnIntegrationsPackageData.  # noqa: E501
        :rtype: str
        """
        return self._keptnversion

    @keptnversion.setter
    def keptnversion(self, keptnversion):
        """Sets the keptnversion of this KeptnIntegrationsPackageData.


        :param keptnversion: The keptnversion of this KeptnIntegrationsPackageData.  # noqa: E501
        :type: str
        """

        self._keptnversion = keptnversion

    @property
    def keptnkind(self):
        """Gets the keptnkind of this KeptnIntegrationsPackageData.  # noqa: E501


        :return: The keptnkind of this KeptnIntegrationsPackageData.  # noqa: E501
        :rtype: str
        """
        return self._keptnkind

    @keptnkind.setter
    def keptnkind(self, keptnkind):
        """Sets the keptnkind of this KeptnIntegrationsPackageData.


        :param keptnkind: The keptnkind of this KeptnIntegrationsPackageData.  # noqa: E501
        :type: str
        """

        self._keptnkind = keptnkind

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeptnIntegrationsPackageData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeptnIntegrationsPackageData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
