# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OLMPackageData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_global_operator': 'bool',
        'custom_resources_definitions': 'list[HelmPackageCrds]',
        'custom_resources_definitions_examples': 'str'
    }

    attribute_map = {
        'is_global_operator': 'isGlobalOperator',
        'custom_resources_definitions': 'customResourcesDefinitions',
        'custom_resources_definitions_examples': 'customResourcesDefinitionsExamples'
    }

    def __init__(self, is_global_operator=None, custom_resources_definitions=None, custom_resources_definitions_examples=None):  # noqa: E501
        """OLMPackageData - a model defined in Swagger"""  # noqa: E501
        self._is_global_operator = None
        self._custom_resources_definitions = None
        self._custom_resources_definitions_examples = None
        self.discriminator = None
        self.is_global_operator = is_global_operator
        if custom_resources_definitions is not None:
            self.custom_resources_definitions = custom_resources_definitions
        if custom_resources_definitions_examples is not None:
            self.custom_resources_definitions_examples = custom_resources_definitions_examples

    @property
    def is_global_operator(self):
        """Gets the is_global_operator of this OLMPackageData.  # noqa: E501


        :return: The is_global_operator of this OLMPackageData.  # noqa: E501
        :rtype: bool
        """
        return self._is_global_operator

    @is_global_operator.setter
    def is_global_operator(self, is_global_operator):
        """Sets the is_global_operator of this OLMPackageData.


        :param is_global_operator: The is_global_operator of this OLMPackageData.  # noqa: E501
        :type: bool
        """
        if is_global_operator is None:
            raise ValueError("Invalid value for `is_global_operator`, must not be `None`")  # noqa: E501

        self._is_global_operator = is_global_operator

    @property
    def custom_resources_definitions(self):
        """Gets the custom_resources_definitions of this OLMPackageData.  # noqa: E501


        :return: The custom_resources_definitions of this OLMPackageData.  # noqa: E501
        :rtype: list[HelmPackageCrds]
        """
        return self._custom_resources_definitions

    @custom_resources_definitions.setter
    def custom_resources_definitions(self, custom_resources_definitions):
        """Sets the custom_resources_definitions of this OLMPackageData.


        :param custom_resources_definitions: The custom_resources_definitions of this OLMPackageData.  # noqa: E501
        :type: list[HelmPackageCrds]
        """

        self._custom_resources_definitions = custom_resources_definitions

    @property
    def custom_resources_definitions_examples(self):
        """Gets the custom_resources_definitions_examples of this OLMPackageData.  # noqa: E501


        :return: The custom_resources_definitions_examples of this OLMPackageData.  # noqa: E501
        :rtype: str
        """
        return self._custom_resources_definitions_examples

    @custom_resources_definitions_examples.setter
    def custom_resources_definitions_examples(self, custom_resources_definitions_examples):
        """Sets the custom_resources_definitions_examples of this OLMPackageData.


        :param custom_resources_definitions_examples: The custom_resources_definitions_examples of this OLMPackageData.  # noqa: E501
        :type: str
        """

        self._custom_resources_definitions_examples = custom_resources_definitions_examples

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OLMPackageData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OLMPackageData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
