# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from artifacthub_client.models.organization_summary import OrganizationSummary  # noqa: F401,E501

class Organization(OrganizationSummary):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'members_count': 'int',
        'confirmed': 'bool'
    }
    if hasattr(OrganizationSummary, "swagger_types"):
        swagger_types.update(OrganizationSummary.swagger_types)

    attribute_map = {
        'members_count': 'members_count',
        'confirmed': 'confirmed'
    }
    if hasattr(OrganizationSummary, "attribute_map"):
        attribute_map.update(OrganizationSummary.attribute_map)

    def __init__(self, members_count=None, confirmed=None, *args, **kwargs):  # noqa: E501
        """Organization - a model defined in Swagger"""  # noqa: E501
        self._members_count = None
        self._confirmed = None
        self.discriminator = None
        self.members_count = members_count
        self.confirmed = confirmed
        OrganizationSummary.__init__(self, *args, **kwargs)

    @property
    def members_count(self):
        """Gets the members_count of this Organization.  # noqa: E501


        :return: The members_count of this Organization.  # noqa: E501
        :rtype: int
        """
        return self._members_count

    @members_count.setter
    def members_count(self, members_count):
        """Sets the members_count of this Organization.


        :param members_count: The members_count of this Organization.  # noqa: E501
        :type: int
        """
        if members_count is None:
            raise ValueError("Invalid value for `members_count`, must not be `None`")  # noqa: E501

        self._members_count = members_count

    @property
    def confirmed(self):
        """Gets the confirmed of this Organization.  # noqa: E501


        :return: The confirmed of this Organization.  # noqa: E501
        :rtype: bool
        """
        return self._confirmed

    @confirmed.setter
    def confirmed(self, confirmed):
        """Sets the confirmed of this Organization.


        :param confirmed: The confirmed of this Organization.  # noqa: E501
        :type: bool
        """
        if confirmed is None:
            raise ValueError("Invalid value for `confirmed`, must not be `None`")  # noqa: E501

        self._confirmed = confirmed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Organization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Organization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
