# coding: utf-8

"""
    Artifact Hub

    Find, install and publish Kubernetes packages  # noqa: E501

    OpenAPI spec version: 1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PackageBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package_id': 'str',
        'name': 'str',
        'normalized_name': 'str',
        'logo_image_id': 'str',
        'display_name': 'str',
        'description': 'str',
        'version': 'str',
        'app_version': 'str',
        'license': 'str',
        'deprecated': 'bool',
        'signed': 'bool',
        'signatures': 'list[str]',
        'official': 'bool',
        'cncf': 'bool',
        'ts': 'int',
        'repository': 'RepositorySummary',
        'security_report_summary': 'PackageBaseSecurityReportSummary',
        'all_containers_images_whitelisted': 'bool',
        'production_organizations_count': 'float'
    }

    attribute_map = {
        'package_id': 'package_id',
        'name': 'name',
        'normalized_name': 'normalized_name',
        'logo_image_id': 'logo_image_id',
        'display_name': 'display_name',
        'description': 'description',
        'version': 'version',
        'app_version': 'app_version',
        'license': 'license',
        'deprecated': 'deprecated',
        'signed': 'signed',
        'signatures': 'signatures',
        'official': 'official',
        'cncf': 'cncf',
        'ts': 'ts',
        'repository': 'repository',
        'security_report_summary': 'security_report_summary',
        'all_containers_images_whitelisted': 'all_containers_images_whitelisted',
        'production_organizations_count': 'production_organizations_count'
    }

    def __init__(self, package_id=None, name=None, normalized_name=None, logo_image_id=None, display_name=None, description=None, version=None, app_version=None, license=None, deprecated=None, signed=None, signatures=None, official=None, cncf=None, ts=None, repository=None, security_report_summary=None, all_containers_images_whitelisted=None, production_organizations_count=None):  # noqa: E501
        """PackageBase - a model defined in Swagger"""  # noqa: E501
        self._package_id = None
        self._name = None
        self._normalized_name = None
        self._logo_image_id = None
        self._display_name = None
        self._description = None
        self._version = None
        self._app_version = None
        self._license = None
        self._deprecated = None
        self._signed = None
        self._signatures = None
        self._official = None
        self._cncf = None
        self._ts = None
        self._repository = None
        self._security_report_summary = None
        self._all_containers_images_whitelisted = None
        self._production_organizations_count = None
        self.discriminator = None
        self.package_id = package_id
        self.name = name
        self.normalized_name = normalized_name
        if logo_image_id is not None:
            self.logo_image_id = logo_image_id
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description
        self.version = version
        if app_version is not None:
            self.app_version = app_version
        if license is not None:
            self.license = license
        if deprecated is not None:
            self.deprecated = deprecated
        if signed is not None:
            self.signed = signed
        if signatures is not None:
            self.signatures = signatures
        if official is not None:
            self.official = official
        if cncf is not None:
            self.cncf = cncf
        self.ts = ts
        self.repository = repository
        if security_report_summary is not None:
            self.security_report_summary = security_report_summary
        if all_containers_images_whitelisted is not None:
            self.all_containers_images_whitelisted = all_containers_images_whitelisted
        if production_organizations_count is not None:
            self.production_organizations_count = production_organizations_count

    @property
    def package_id(self):
        """Gets the package_id of this PackageBase.  # noqa: E501


        :return: The package_id of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id):
        """Sets the package_id of this PackageBase.


        :param package_id: The package_id of this PackageBase.  # noqa: E501
        :type: str
        """
        if package_id is None:
            raise ValueError("Invalid value for `package_id`, must not be `None`")  # noqa: E501

        self._package_id = package_id

    @property
    def name(self):
        """Gets the name of this PackageBase.  # noqa: E501


        :return: The name of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PackageBase.


        :param name: The name of this PackageBase.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def normalized_name(self):
        """Gets the normalized_name of this PackageBase.  # noqa: E501


        :return: The normalized_name of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._normalized_name

    @normalized_name.setter
    def normalized_name(self, normalized_name):
        """Sets the normalized_name of this PackageBase.


        :param normalized_name: The normalized_name of this PackageBase.  # noqa: E501
        :type: str
        """
        if normalized_name is None:
            raise ValueError("Invalid value for `normalized_name`, must not be `None`")  # noqa: E501

        self._normalized_name = normalized_name

    @property
    def logo_image_id(self):
        """Gets the logo_image_id of this PackageBase.  # noqa: E501


        :return: The logo_image_id of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._logo_image_id

    @logo_image_id.setter
    def logo_image_id(self, logo_image_id):
        """Sets the logo_image_id of this PackageBase.


        :param logo_image_id: The logo_image_id of this PackageBase.  # noqa: E501
        :type: str
        """

        self._logo_image_id = logo_image_id

    @property
    def display_name(self):
        """Gets the display_name of this PackageBase.  # noqa: E501


        :return: The display_name of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this PackageBase.


        :param display_name: The display_name of this PackageBase.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this PackageBase.  # noqa: E501


        :return: The description of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PackageBase.


        :param description: The description of this PackageBase.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def version(self):
        """Gets the version of this PackageBase.  # noqa: E501


        :return: The version of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PackageBase.


        :param version: The version of this PackageBase.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def app_version(self):
        """Gets the app_version of this PackageBase.  # noqa: E501


        :return: The app_version of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._app_version

    @app_version.setter
    def app_version(self, app_version):
        """Sets the app_version of this PackageBase.


        :param app_version: The app_version of this PackageBase.  # noqa: E501
        :type: str
        """

        self._app_version = app_version

    @property
    def license(self):
        """Gets the license of this PackageBase.  # noqa: E501


        :return: The license of this PackageBase.  # noqa: E501
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this PackageBase.


        :param license: The license of this PackageBase.  # noqa: E501
        :type: str
        """

        self._license = license

    @property
    def deprecated(self):
        """Gets the deprecated of this PackageBase.  # noqa: E501


        :return: The deprecated of this PackageBase.  # noqa: E501
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """Sets the deprecated of this PackageBase.


        :param deprecated: The deprecated of this PackageBase.  # noqa: E501
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def signed(self):
        """Gets the signed of this PackageBase.  # noqa: E501


        :return: The signed of this PackageBase.  # noqa: E501
        :rtype: bool
        """
        return self._signed

    @signed.setter
    def signed(self, signed):
        """Sets the signed of this PackageBase.


        :param signed: The signed of this PackageBase.  # noqa: E501
        :type: bool
        """

        self._signed = signed

    @property
    def signatures(self):
        """Gets the signatures of this PackageBase.  # noqa: E501


        :return: The signatures of this PackageBase.  # noqa: E501
        :rtype: list[str]
        """
        return self._signatures

    @signatures.setter
    def signatures(self, signatures):
        """Sets the signatures of this PackageBase.


        :param signatures: The signatures of this PackageBase.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["prov", "cosign"]  # noqa: E501
        if not set(signatures).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `signatures` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(signatures) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._signatures = signatures

    @property
    def official(self):
        """Gets the official of this PackageBase.  # noqa: E501


        :return: The official of this PackageBase.  # noqa: E501
        :rtype: bool
        """
        return self._official

    @official.setter
    def official(self, official):
        """Sets the official of this PackageBase.


        :param official: The official of this PackageBase.  # noqa: E501
        :type: bool
        """

        self._official = official

    @property
    def cncf(self):
        """Gets the cncf of this PackageBase.  # noqa: E501


        :return: The cncf of this PackageBase.  # noqa: E501
        :rtype: bool
        """
        return self._cncf

    @cncf.setter
    def cncf(self, cncf):
        """Sets the cncf of this PackageBase.


        :param cncf: The cncf of this PackageBase.  # noqa: E501
        :type: bool
        """

        self._cncf = cncf

    @property
    def ts(self):
        """Gets the ts of this PackageBase.  # noqa: E501


        :return: The ts of this PackageBase.  # noqa: E501
        :rtype: int
        """
        return self._ts

    @ts.setter
    def ts(self, ts):
        """Sets the ts of this PackageBase.


        :param ts: The ts of this PackageBase.  # noqa: E501
        :type: int
        """
        if ts is None:
            raise ValueError("Invalid value for `ts`, must not be `None`")  # noqa: E501

        self._ts = ts

    @property
    def repository(self):
        """Gets the repository of this PackageBase.  # noqa: E501


        :return: The repository of this PackageBase.  # noqa: E501
        :rtype: RepositorySummary
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this PackageBase.


        :param repository: The repository of this PackageBase.  # noqa: E501
        :type: RepositorySummary
        """
        if repository is None:
            raise ValueError("Invalid value for `repository`, must not be `None`")  # noqa: E501

        self._repository = repository

    @property
    def security_report_summary(self):
        """Gets the security_report_summary of this PackageBase.  # noqa: E501


        :return: The security_report_summary of this PackageBase.  # noqa: E501
        :rtype: PackageBaseSecurityReportSummary
        """
        return self._security_report_summary

    @security_report_summary.setter
    def security_report_summary(self, security_report_summary):
        """Sets the security_report_summary of this PackageBase.


        :param security_report_summary: The security_report_summary of this PackageBase.  # noqa: E501
        :type: PackageBaseSecurityReportSummary
        """

        self._security_report_summary = security_report_summary

    @property
    def all_containers_images_whitelisted(self):
        """Gets the all_containers_images_whitelisted of this PackageBase.  # noqa: E501


        :return: The all_containers_images_whitelisted of this PackageBase.  # noqa: E501
        :rtype: bool
        """
        return self._all_containers_images_whitelisted

    @all_containers_images_whitelisted.setter
    def all_containers_images_whitelisted(self, all_containers_images_whitelisted):
        """Sets the all_containers_images_whitelisted of this PackageBase.


        :param all_containers_images_whitelisted: The all_containers_images_whitelisted of this PackageBase.  # noqa: E501
        :type: bool
        """

        self._all_containers_images_whitelisted = all_containers_images_whitelisted

    @property
    def production_organizations_count(self):
        """Gets the production_organizations_count of this PackageBase.  # noqa: E501


        :return: The production_organizations_count of this PackageBase.  # noqa: E501
        :rtype: float
        """
        return self._production_organizations_count

    @production_organizations_count.setter
    def production_organizations_count(self, production_organizations_count):
        """Sets the production_organizations_count of this PackageBase.


        :param production_organizations_count: The production_organizations_count of this PackageBase.  # noqa: E501
        :type: float
        """

        self._production_organizations_count = production_organizations_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
